"""
Pseudo-spectral solver for the incompressible Navier-Stokes equations.

The solver works in the rotational form of the incompressible Navier-Stokes
equation and integrates the Fourier representation of the velocity field in
time. All fast Fourier transforms and the underlying (optionally MPI-parallel)
data layout are provided by µGrid's :class:`muGrid.FFTEngine`.

Notes on the µGrid field interface
----------------------------------
* Fields are obtained from the engine with ``real_space_field(name, ncomp)``
  and ``fourier_space_field(name, ncomp)``. Repeated calls with the same name
  return the *same* field (and hence reuse the same memory).
* The numpy view of a field is exposed through the ``.p`` (pixel layout)
  property. This view is writable in place (``field.p[...] = value``) but the
  property itself has no setter, so plain assignment (``field.p = value``) is
  not possible.
"""

import numpy as np

from NuMPI.Tools import Reduction

from muGrid import FFTEngine


class NavierStokes:
    def __init__(self, nb_grid_pts, physical_size=(1, 1, 1), viscosity=0.001, dealias=True, communicator=None):
        self._nb_grid_pts = nb_grid_pts
        self._physical_size = physical_size
        self._viscosity = viscosity
        self._dealias = dealias
        self._communicator = communicator

        self._init_fft()

    def _init_fft(self):
        # Parallel reduction helper and grid spacing
        self._parnp = Reduction(self._communicator)
        self._grid_spacing = np.array(self._physical_size) / np.array(self._nb_grid_pts)

        # FFT engine (µGrid selects PocketFFT on the CPU, cuFFT/rocFFT on the GPU)
        self._fft = FFTEngine(self._nb_grid_pts, communicator=self._communicator)

        # Angular wavevectors k = 2 pi * fftfreq / dx, shape (3, *fourier_subdomain)
        self._wavevector_cqks = (2 * np.pi * self._fft.fftfreq.T / self._grid_spacing).T
        self._wavevector_sq_qks = np.sum(self._wavevector_cqks ** 2, axis=0)  # |k|^2
        self._zero_wavevector_qks = self._wavevector_sq_qks == 0  # the k = 0 mode
        self._zero_wavevectorx_qks = self._wavevector_cqks[0] == 0  # the kx = 0 plane

        # k / |k|^2 for the pressure (Leray) projection. The k = 0 entry is set
        # to zero; the projection leaves the mean flow untouched anyway.
        nonzero_sq_qks = np.where(self._zero_wavevector_qks, 1.0, self._wavevector_sq_qks)
        self._inv_wavevector_cqks = self._wavevector_cqks / nonzero_sq_qks

        # 2/3-rule dealiasing mask: True for the retained (lower 2/3) modes
        cutoff = 2 * np.pi / (3 * self._grid_spacing)
        self._dealias_qks = np.all((np.abs(self._wavevector_cqks).T < cutoff).T, axis=0)

    @property
    def fft(self):
        """The underlying :class:`muGrid.FFTEngine`."""
        return self._fft

    @property
    def parnp(self):
        """Parallel reduction helper (MPI-aware ``min``/``max``/``mean``/``sum``)."""
        return self._parnp

    @property
    def wavevector_sq(self):
        """Squared wavevector magnitude ``|k|^2`` (Fourier-space array)."""
        return self._wavevector_sq_qks

    def dudt(self, t, uarr_cqks):
        """
        This function implements the incompressible Navier-Stokes equation in its
        rotational form. It computes the time derivative of the Fourier-representation
        of the velocity field.

        Parameters
        ----------
        t : float
            The current time.
        uarr_cqks : array_like
            The current value of the Fourier-representation of the velocity field.

        Returns
        -------
        array_like
            The time derivative of the Fourier-representation of the velocity field.
        """
        # Get fields; this will reuse the same memory upon every call
        u_cqks = self._fft.fourier_space_field('u_cqks', 3)
        u_cxyz = self._fft.real_space_field('u_cxyz', 3)
        curlu_cqks = self._fft.fourier_space_field('curlu_cqks', 3)
        curlu_cxyz = self._fft.real_space_field('curlu_cxyz', 3)
        ucurlu_cqks = self._fft.fourier_space_field('ucurlu_cqks', 3)
        ucurlu_cxyz = self._fft.real_space_field('ucurlu_cxyz', 3)

        # Copy numpy array to field (in-place; µGrid's `.p` has no setter)
        u_cqks.p[...] = uarr_cqks

        # Compute the vorticity (curl) in Fourier space: omega = i k x u
        curlu_cqks.p[...] = np.cross(self._wavevector_cqks * 1j, u_cqks.p, axis=0)
        # 2/3-rule dealiasing: band-limit the velocity and vorticity to the
        # lower 2/3 of the spectrum *before* forming the nonlinear product in
        # real space. This keeps the aliasing error generated by the quadratic
        # product out of the resolved modes.
        if self._dealias:
            u_cqks.p[...] *= self._dealias_qks
            curlu_cqks.p[...] *= self._dealias_qks
        self._fft.ifft(u_cqks, u_cxyz)
        self._fft.ifft(curlu_cqks, curlu_cxyz)
        ucurlu_cxyz.p[...] = np.cross(u_cxyz.p, curlu_cxyz.p, axis=0)
        self._fft.fft(ucurlu_cxyz, ucurlu_cqks)
        ucurlu_cqks.p[...] *= self._fft.normalisation
        # Discard the aliased high-wavenumber band of the nonlinear term so that
        # no spurious energy is injected into the cut-off modes (they then only
        # experience viscous decay).
        if self._dealias:
            ucurlu_cqks.p[...] *= self._dealias_qks

        # Navier-Stokes equation: u x omega - nu k^2 u, projected onto the
        # divergence-free subspace (the last term is the pressure projection).
        return ucurlu_cqks.p \
            - self._viscosity * self._wavevector_sq_qks * uarr_cqks \
            - self._wavevector_cqks * np.sum(self._inv_wavevector_cqks * ucurlu_cqks.p, axis=0)

    def power(self, u_cqks, mask=None):
        """
        Total (or masked) spectral energy of the velocity field via Parseval's
        theorem. The factor of two accounts for the half-complex (r2c) storage;
        the kx = 0 plane is not doubled.
        """
        p = 2 * np.sum(np.real(u_cqks * np.conj(u_cqks)), axis=0)
        p[self._zero_wavevectorx_qks] -= np.sum(
            np.real(u_cqks[:, self._zero_wavevectorx_qks] * np.conj(u_cqks[:, self._zero_wavevectorx_qks])), axis=0)
        if mask is None:
            return self._parnp.sum(p) / self._fft.normalisation
        else:
            return self._parnp.sum(p[mask]) / self._fft.normalisation

    def to_incompressible(self, u_cqks):
        """Project a Fourier-space velocity field onto the divergence-free subspace."""
        return u_cqks - np.sum(u_cqks * self._wavevector_cqks, axis=0) * self._inv_wavevector_cqks
